server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfiguration:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "https://educeasy.fr"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: core
          uri: http://educeasy-core:4700
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
