app:
  url: ${DB_URL:http://localhost:8080}
  security:
    jwt-secret: ${JWT_SECRET}
    jwt-expiration-minutes: 30
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/educeasy_db?useSSL=false&serverTimezone=UTC}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
      hibernate.show_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    validate-on-migrate: true
    clean-disabled: true
    baseline-on-migrate: true
    baseline-version: 0.0.0.0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8
server:
  port: 4700
  error:
    include-message: always
    include-binding-errors: always
logging.level.org.springframework.security: INFO
